version: '3.4'
services:

  therunninggame-frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    depends_on:
      - therunninggame-backend
    command: npm run preview
    restart: unless-stopped
    # ports:
    #   - 8082:8080
    networks:
      - therunninggame
      - service-routing
    environment:
      VITE_BACKEND_SERVICE_URL: ${VITE_BACKEND_SERVICE_URL}
      VITE_SESSION_COOKIE_NAME: ${VITE_SESSION_COOKIE_NAME}

  therunninggame-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - database
    command: uvicorn service:app --host 0.0.0.0 --root-path /api --port 8080
    restart: unless-stopped
    # ports:
    #   - 8081:8080
    networks:
      - therunninggame
      - service-routing
    environment:
      BACKEND_DATABASE_CONNECTION_STRING: ${BACKEND_DATABASE_CONNECTION_STRING}

      BACKEND_SERVICE_URL: ${BACKEND_SERVICE_URL}
      FRONTEND_URL: ${FRONTEND_URL}

      STRAVA_CLIENT_ID: ${STRAVA_CLIENT_ID}
      STRAVA_CLIENT_SECRET: ${STRAVA_CLIENT_SECRET}

      VITE_BACKEND_SERVICE_URL: ${VITE_BACKEND_SERVICE_URL}
      VITE_SESSION_COOKIE_NAME: ${VITE_SESSION_COOKIE_NAME}

  database:
    image: postgres:16-bullseye
    restart: unless-stopped
    volumes:
      - ./data/postgres:/data/postgres
    ports:
      - "54321:5432"
    networks:
      - therunninggame
    environment:
      POSTGRES_USER: ${BACKEND_DATABASE_USER}
      POSTGRES_PASSWORD: ${BACKEND_DATABASE_PASSWORD}
      POSTGRES_DB: ${BACKEND_DATABASE_DATABASE}
      PGDATA: /data/postgres

networks:
  therunninggame:
    name: therunninggame
  service-routing:
    external: true
    name: service-routing
