version: '3.4'
services:

  therunninggame-frontend:
    ports:
      - 8080:8080
    networks:
      - therunninggame

  therunninggame-backend:
    command: uvicorn service:app --host 0.0.0.0 --port 8080
    ports:
      - 8081:8080
    networks:
      - therunninggame
