version: '3.4'
services:

  therunninggame-backend:
    command:
      - "sh"
      - "-c"
      - "pip install debugpy && python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn service:app --reload --host 0.0.0.0 --port 8080"
    ports:
      - 5678:5678
    volumes:
      - ./backend:/app
